name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    -name: Install depencies
      run: npm install
    - name: Run testa
      run: npm run
